class GraphBuilder:
    def __init__(self) -> None: ...
    def add_output(self) -> Node: ...
    def sine_osc(self) -> Node: ...
    def build_runtime(self) -> Runtime: ...


class Node:
    def __init__(self) -> None: ...
    def input(self, index) -> Input: ...
    def output(self, index) -> Output: ...


class Output:
    def __init__(self) -> None: ...
    def connect(self, input: Input) -> None: ...


class Input:
    def __init__(self) -> None: ...
    def connect(self, output: Output) -> None: ...
    def set(self, value) -> None: ...


class Runtime:
    def run_for(self, seconds: float) -> None: ...
